apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "motioneye"
  name: "motioneye-videos"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "2Gi"