---
apiVersion: v1
kind: Service
metadata:
  name: motioneye-service
spec:
  selector:
    app: motioneye
  ports:
    - port: 8765
      targetPort: 8765
      name: web
    - port: 7999
      targetPort: 7999
      name: motion
  type: LoadBalancer