apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "motioneye"
  name: "motioneye-config"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "500Mi"