apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "zigbee2mqtt"
  name: "zigbee2mqtt"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "500Mi"